from .applicant import *
from .grading import *
from .learning import *
from .news import *
from .people import *
from .requests import *
from .role import *
from .schedule import *
from .university import *