# Generated by Django 5.2.8 on 2025-11-12 21:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('desired_program', models.CharField(max_length=255, verbose_name='Желаемая программа')),
                ('study_form', models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Очно-заочная'), ('extramural', 'Заочная')], default='full_time', max_length=20, verbose_name='Форма обучения')),
                ('previous_education', models.CharField(blank=True, max_length=255, verbose_name='Предыдущее образование')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('review', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Заявление на поступление',
                'verbose_name_plural': 'Заявления на поступление',
            },
        ),
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('desired_program', models.CharField(max_length=255, verbose_name='Желаемая программа')),
                ('study_form', models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Очно-заочная'), ('extramural', 'Заочная')], default='full_time', max_length=20, verbose_name='Форма обучения')),
                ('previous_education', models.CharField(blank=True, max_length=255, verbose_name='Предыдущее образование')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('review', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Заявление на поступление',
                'verbose_name_plural': 'Заявления на поступление',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('hw', 'Домашнее задание'), ('quiz', 'Тест/Квиз'), ('lab', 'Лабораторная'), ('exam', 'Экзамен'), ('project', 'Проект'), ('other', 'Другое')], max_length=16)),
                ('max_points', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Вес в итоговой оценке (сумма по курсу может быть 1.0 или 100)', max_digits=5)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical', 'Техническая проблема'), ('study', 'Учебные вопросы'), ('schedule', 'Проблемы с расписанием'), ('profile', 'Проблемы с профилем'), ('other', 'Другое')], default='technical', max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='Email для обратной связи')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема обращения')),
                ('description', models.TextField(verbose_name='Подробное описание проблемы')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10)),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочная проблема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('resolved', 'Решено')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Обращение в поддержку',
                'verbose_name_plural': 'Обращения в поддержку',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('Moderator_3lvl', 'Модератор 3ур.'), ('Moderator_2lvl', 'Модератор 2ур.'), ('Moderator_1lvl', 'Модератор 1ур.'), ('Teacher', 'Учитель'), ('Journalist', 'Журналист'), ('Headman', 'Модерация группы'), ('Student', 'Студент'), ('Applicant', 'Абитуриент'), ('Guest', 'Гость')], max_length=64)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('week_parity', models.CharField(choices=[('all', 'Каждую'), ('odd', 'Нечётные'), ('even', 'Чётные')], default='all', max_length=5, verbose_name='Чётность недели')),
                ('start_date', models.DateField(verbose_name='Дата начала периода')),
                ('end_date', models.DateField(verbose_name='Дата окончания периода')),
                ('building', models.CharField(blank=True, max_length=64, verbose_name='Корпус')),
                ('room', models.CharField(blank=True, max_length=32, verbose_name='Аудитория')),
                ('note', models.CharField(blank=True, max_length=128, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название университета')),
                ('short_name', models.CharField(max_length=64, unique=True, verbose_name='Короткое имя')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Город')),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('ects', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'unique_together': {('code', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('vk_user_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='VK/Max user id')),
                ('user', models.OneToOneField(blank=True, help_text='Связь с Django User (если есть)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='main.role')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='main.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('hours', models.PositiveSmallIntegerField(default=0)),
                ('control_form', models.CharField(choices=[('exam', 'Экзамен'), ('test', 'Зачет'), ('diff_test', 'Дифф. зачет')], default='exam', max_length=32)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_items', to='main.discipline')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='main.program')),
            ],
            options={
                'unique_together': {('program', 'discipline', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('action', models.CharField(choices=[('cancel', 'Отмена'), ('move', 'Перенос'), ('change_room', 'Смена аудитории/примечания')], max_length=12, verbose_name='Действие')),
                ('new_date', models.DateField(blank=True, null=True, verbose_name='Новая дата')),
                ('new_start_time', models.TimeField(blank=True, null=True, verbose_name='Новое начало')),
                ('new_end_time', models.TimeField(blank=True, null=True, verbose_name='Новый конец')),
                ('new_building', models.CharField(blank=True, max_length=64, verbose_name='Новый корпус')),
                ('new_room', models.CharField(blank=True, max_length=32, verbose_name='Новая аудитория')),
                ('new_note', models.CharField(blank=True, max_length=128, verbose_name='Новое примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='main.scheduleslot', verbose_name='Ячейка')),
            ],
            options={
                'ordering': ['date', 'slot_id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32, unique=True, verbose_name='Номер студенческого билета')),
                ('current_year', models.PositiveSmallIntegerField(help_text='Курс (1..6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('admission_year', models.PositiveSmallIntegerField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('points', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('grade_5', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('grade_ects', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('FX', 'FX'), ('F', 'F')], max_length=2)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='main.person')),
                ('linked_student', models.OneToOneField(blank=True, help_text='Связь после зачисления', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('admission_year', models.PositiveSmallIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='main.program')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='main.studentgroup'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='schedule_slots', to='main.studentgroup', verbose_name='Группы'),
        ),
        migrations.CreateModel(
            name='StudentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('headman', 'Староста'), ('journalist', 'Журналист'), ('TUO', 'Профорг')], max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_title', models.CharField(blank=True, max_length=128)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='main.person')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main.university')),
            ],
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curating_groups', to='main.teacher'),
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester_in_year', models.PositiveSmallIntegerField(choices=[(1, 'осенний'), (2, 'весенний')])),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachings', to='main.curriculum')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachings', to='main.studentgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachings', to='main.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='teaching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='main.teaching', verbose_name='Курс (Teaching)'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.student')),
                ('teaching', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='main.teaching')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='teaching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='main.teaching'),
        ),
        migrations.CreateModel(
            name='TeacherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('annual', 'Ежегодный отпуск'), ('sick', 'Больничный'), ('academic', 'Академический отпуск'), ('business', 'Командировка'), ('other', 'Иное')], max_length=64)),
                ('status', models.CharField(choices=[('submitted', 'Отправлено'), ('in_review', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='submitted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.teacher')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_requests', to='main.university')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('certificate_enrollment', 'Справка об обучении'), ('certificate_income', 'Справка о доходах/стипендии'), ('dormitory', 'Общежитие'), ('practice', 'Практика/стажировка'), ('other', 'Прочее')], max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('in_progress', 'В работе'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('issued', 'Выдано')], default='submitted', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='main.university')),
            ],
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.university'),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.university'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='main.university', verbose_name='Университет'),
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_icon', models.CharField(max_length=8, verbose_name='Эмодзи')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст новости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news_covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='main.university')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='🔔', max_length=8, verbose_name='Иконка/эмодзи')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_notifications', to='main.person')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.studentgroup')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_notifications', to='main.university')),
            ],
            options={
                'verbose_name': 'Групповое оповещение',
                'verbose_name_plural': 'Групповые оповещения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='main.university'),
        ),
        migrations.CreateModel(
            name='ApplicantExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('exam_type', models.CharField(choices=[('USE', 'ЕГЭ'), ('internal', 'Внутренний'), ('other', 'Другое')], default='USE', max_length=16)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='main.applicant')),
            ],
            options={
                'unique_together': {('applicant', 'subject', 'exam_type')},
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['vk_user_id'], name='main_person_vk_user_8a42a4_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleexception',
            index=models.Index(fields=['date', 'action'], name='main_schedu_date_ad0a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['student', 'graded_at'], name='main_assess_student_616ec7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentresult',
            unique_together={('assessment', 'student', 'attempt')},
        ),
        migrations.AddIndex(
            model_name='studentrole',
            index=models.Index(fields=['role', 'start_date'], name='main_studen_role_1c82f1_idx'),
        ),
        migrations.AddIndex(
            model_name='teaching',
            index=models.Index(fields=['academic_year'], name='main_teachi_academi_5fecce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('teacher', 'curriculum', 'group', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active'], name='main_enroll_is_acti_958dd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'teaching')},
        ),
        migrations.AddIndex(
            model_name='studentgroup',
            index=models.Index(fields=['admission_year'], name='main_studen_admissi_9ee645_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together={('program', 'name')},
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['university', 'weekday', 'start_time'], name='main_schedu_univers_b174f6_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['start_date', 'end_date'], name='main_schedu_start_d_5790e3_idx'),
        ),
        migrations.AddIndex(
            model_name='groupnotification',
            index=models.Index(fields=['group', 'created_at'], name='main_groupn_group_i_5dd7b1_idx'),
        ),
    ]
