# Generated by Django 4.2.11 on 2025-11-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Абитуриент', 'verbose_name_plural': 'Абитуриенты'},
        ),
        migrations.AlterModelOptions(
            name='applicantexam',
            options={'verbose_name': 'Результат экзамена абитуриента', 'verbose_name_plural': 'Результаты экзаменов абитуриента'},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'Учебный план', 'verbose_name_plural': 'Учебные планы'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-published_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программа обучения', 'verbose_name_plural': 'Программы обучения'},
        ),
        migrations.AlterModelOptions(
            name='scheduleexception',
            options={'ordering': ['date', 'slot_id'], 'verbose_name': 'Пара (перенос)', 'verbose_name_plural': 'Пары (перенос)'},
        ),
        migrations.AlterModelOptions(
            name='scheduleslot',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='studentrequest',
            options={'verbose_name': 'Заявление студента', 'verbose_name_plural': 'Заявления студентов'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='teacherrequest',
            options={'verbose_name': 'Заявление преподавателя', 'verbose_name_plural': 'Заявления преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teaching',
            options={'verbose_name': 'Учебный курс', 'verbose_name_plural': 'Учебные курсы'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Университет', 'verbose_name_plural': 'Университеты'},
        ),
    ]
