# Generated by Django 5.2.8 on 2025-11-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faculty_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='main.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'name')},
            },
        ),
    ]
