# Generated by Django 5.2.8 on 2025-11-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название университета')),
                ('short_name', models.CharField(max_length=64, unique=True, verbose_name='Короткое имя')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Город')),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_title', models.CharField(blank=True, max_length=128)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='main.person')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main.university')),
            ],
        ),
    ]
