# Generated by Django 5.2.8 on 2025-11-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_university_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='main.university'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
