# Generated by Django 5.2.8 on 2025-11-08 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_faculty_university_alter_faculty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('admission_year', models.PositiveSmallIntegerField()),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curating_groups', to='main.teacher')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='main.program')),
            ],
            options={
                'indexes': [models.Index(fields=['admission_year'], name='main_studen_admissi_9ee645_idx')],
                'unique_together': {('program', 'name')},
            },
        ),
    ]
