# Generated by Django 5.2.8 on 2025-11-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_studentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('ects', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'unique_together': {('code', 'title')},
            },
        ),
    ]
