# Generated by Django 5.2.8 on 2025-11-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
