# Generated by Django 5.2.8 on 2025-11-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_discipline_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('hours', models.PositiveSmallIntegerField(default=0)),
                ('control_form', models.CharField(choices=[('exam', 'Экзамен'), ('test', 'Зачет'), ('diff_test', 'Дифф. зачет')], default='exam', max_length=32)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_items', to='main.discipline')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='main.program')),
            ],
            options={
                'unique_together': {('program', 'discipline', 'semester')},
            },
        ),
    ]
