# Generated by Django 5.2.8 on 2025-11-08 15:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.university'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32, unique=True, verbose_name='Номер студенческого билета')),
                ('current_year', models.PositiveSmallIntegerField(help_text='Курс (1..6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('admission_year', models.PositiveSmallIntegerField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='main.person')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='main.studentgroup')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.university')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('headman', 'Староста'), ('journalist', 'Журналист'), ('TUO', 'Профорг')], max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='main.student')),
            ],
            options={
                'indexes': [models.Index(fields=['role', 'start_date'], name='main_studen_role_1c82f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester_in_year', models.PositiveSmallIntegerField(choices=[(1, 'осенний'), (2, 'весенний')])),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachings', to='main.curriculum')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachings', to='main.studentgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachings', to='main.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['academic_year'], name='main_teachi_academi_5fecce_idx')],
                'unique_together': {('teacher', 'curriculum', 'group', 'academic_year')},
            },
        ),
    ]
