# Generated by Django 5.2.8 on 2025-11-08 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_studentgroup_university_student_studentrole_teaching'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('hw', 'Домашнее задание'), ('quiz', 'Тест/Квиз'), ('lab', 'Лабораторная'), ('exam', 'Экзамен'), ('project', 'Проект'), ('other', 'Другое')], max_length=16)),
                ('max_points', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Вес в итоговой оценке (сумма по курсу может быть 1.0 или 100)', max_digits=5)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('teaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='main.teaching')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('points', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('grade_5', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('grade_ects', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('FX', 'FX'), ('F', 'F')], max_length=2)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='main.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'graded_at'], name='main_assess_student_616ec7_idx')],
                'unique_together': {('assessment', 'student', 'attempt')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.student')),
                ('teaching', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='main.teaching')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='main_enroll_is_acti_958dd0_idx')],
                'unique_together': {('student', 'teaching')},
            },
        ),
    ]
