# Generated by Django 5.2.8 on 2025-11-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_assessment_assessmentresult_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('certificate_enrollment', 'Справка об обучении'), ('certificate_income', 'Справка о доходах/стипендии'), ('dormitory', 'Общежитие'), ('practice', 'Практика/стажировка'), ('other', 'Прочее')], max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('in_progress', 'В работе'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('issued', 'Выдано')], default='submitted', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='main.university')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('annual', 'Ежегодный отпуск'), ('sick', 'Больничный'), ('academic', 'Академический отпуск'), ('business', 'Командировка'), ('other', 'Иное')], max_length=64)),
                ('status', models.CharField(choices=[('submitted', 'Отправлено'), ('in_review', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='submitted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.teacher')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_requests', to='main.university')),
            ],
        ),
    ]
