# Generated by Django 5.2.8 on 2025-11-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_studentrequest_teacherrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('linked_student', models.OneToOneField(blank=True, help_text='Связь после зачисления', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_rating', to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('under_review', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('enrolled', 'Зачислен')], default='submitted', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='main.program')),
                ('applicant_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.applicant_rating')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'priority'], name='main_admiss_status_fed98f_idx')],
                'unique_together': {('applicant_rating', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ApplicantExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('exam_type', models.CharField(choices=[('ege', 'ЕГЭ'), ('internal', 'Внутренний'), ('other', 'Другое')], default='ege', max_length=16)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applicant_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='main.applicant_rating')),
            ],
            options={
                'unique_together': {('applicant_rating', 'subject', 'exam_type')},
            },
        ),
    ]
