# Generated by Django 5.2.8 on 2025-11-08 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_applicant_admissionrequest_applicantexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrequest',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_request', to='main.program'),
        ),
        migrations.AlterField(
            model_name='applicantexam',
            name='exam_type',
            field=models.CharField(choices=[('USE', 'ЕГЭ'), ('internal', 'Внутренний'), ('other', 'Другое')], default='USE', max_length=16),
        ),
    ]
