# Generated by Django 5.2.8 on 2025-11-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_admissionrequest_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('Moderator_3lvl', 'Модератор 3ур.'), ('Moderator_2lvl', 'Модератор 2ур.'), ('Moderator_1lvl', 'Модератор 1ур.'), ('Teacher', 'Учитель'), ('Journalist', 'Журналист'), ('Headman', 'Модерация группы'), ('Student', 'Студент'), ('Applicant', 'Абитуриент'), ('Guest', 'Гость')])),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
