# Generated by Django 5.2.8 on 2025-11-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_newspost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-published_at']},
        ),
    ]
