# Generated by Django 5.2.8 on 2025-11-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_newspost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='news_icon',
            field=models.CharField(max_length=1, null=True, verbose_name='Эмодзи'),
        ),
    ]
