# Generated by Django 5.2.8 on 2025-11-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_newspost_news_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='news_icon',
            field=models.TextField(verbose_name='Эмодзи'),
        ),
    ]
