# Generated by Django 5.2.8 on 2025-11-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_newspost_news_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='news_icon',
            field=models.CharField(max_length=8, verbose_name='Эмодзи'),
        ),
    ]
