# Generated by Django 5.2.8 on 2025-11-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_newspost_news_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.CharField(choices=[('Moderator_3lvl', 'Модератор 3ур.'), ('Moderator_2lvl', 'Модератор 2ур.'), ('Moderator_1lvl', 'Модератор 1ур.'), ('Teacher', 'Учитель'), ('Journalist', 'Журналист'), ('Headman', 'Модерация группы'), ('Student', 'Студент'), ('Applicant', 'Абитуриент'), ('Guest', 'Гость')], max_length=64),
        ),
    ]
