# Generated by Django 4.2.11 on 2025-11-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_role_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('week_parity', models.CharField(choices=[('all', 'Каждую'), ('odd', 'Нечётные'), ('even', 'Чётные')], default='all', max_length=5, verbose_name='Чётность недели')),
                ('start_date', models.DateField(verbose_name='Дата начала периода')),
                ('end_date', models.DateField(verbose_name='Дата окончания периода')),
                ('building', models.CharField(blank=True, max_length=64, verbose_name='Корпус')),
                ('room', models.CharField(blank=True, max_length=32, verbose_name='Аудитория')),
                ('note', models.CharField(blank=True, max_length=128, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='schedule_slots', to='main.studentgroup', verbose_name='Группы')),
                ('teaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='main.teaching', verbose_name='Курс (Teaching)')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='main.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Ячейка расписания',
                'verbose_name_plural': 'Ячейки расписания',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('action', models.CharField(choices=[('cancel', 'Отмена'), ('move', 'Перенос'), ('change_room', 'Смена аудитории/примечания')], max_length=12, verbose_name='Действие')),
                ('new_date', models.DateField(blank=True, null=True, verbose_name='Новая дата')),
                ('new_start_time', models.TimeField(blank=True, null=True, verbose_name='Новое начало')),
                ('new_end_time', models.TimeField(blank=True, null=True, verbose_name='Новый конец')),
                ('new_building', models.CharField(blank=True, max_length=64, verbose_name='Новый корпус')),
                ('new_room', models.CharField(blank=True, max_length=32, verbose_name='Новая аудитория')),
                ('new_note', models.CharField(blank=True, max_length=128, verbose_name='Новое примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='main.scheduleslot', verbose_name='Ячейка')),
            ],
            options={
                'verbose_name': 'Исключение расписания',
                'verbose_name_plural': 'Исключения расписания',
                'ordering': ['date', 'slot_id'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['university', 'weekday', 'start_time'], name='main_schedu_univers_b174f6_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['start_date', 'end_date'], name='main_schedu_start_d_5790e3_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleexception',
            index=models.Index(fields=['date', 'action'], name='main_schedu_date_ad0a5d_idx'),
        ),
    ]
