# Generated by Django 4.2.11 on 2025-11-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_scheduleslot_scheduleexception_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleexception',
            options={'ordering': ['date', 'slot_id']},
        ),
        migrations.AlterModelOptions(
            name='scheduleslot',
            options={'ordering': ['weekday', 'start_time']},
        ),
    ]
