# Generated by Django 4.2.11 on 2025-11-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_scheduleexception_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical', 'Техническая проблема'), ('study', 'Учебные вопросы'), ('schedule', 'Проблемы с расписанием'), ('profile', 'Проблемы с профилем'), ('other', 'Другое')], default='technical', max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='Email для обратной связи')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема обращения')),
                ('description', models.TextField(verbose_name='Подробное описание проблемы')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10)),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочная проблема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('resolved', 'Решено')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Обращение в поддержку',
                'verbose_name_plural': 'Обращения в поддержку',
            },
        ),
    ]
