# Generated by Django 4.2.11 on 2025-11-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_helprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('desired_program', models.CharField(max_length=255, verbose_name='Желаемая программа')),
                ('study_form', models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Очно-заочная'), ('extramural', 'Заочная')], default='full_time', max_length=20, verbose_name='Форма обучения')),
                ('previous_education', models.CharField(blank=True, max_length=255, verbose_name='Предыдущее образование')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('review', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Заявление на поступление',
                'verbose_name_plural': 'Заявления на поступление',
            },
        ),
    ]
