# Generated by Django 4.2.11 on 2025-11-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_applicationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='🔔', max_length=8, verbose_name='Иконка/эмодзи')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.studentgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_notifications', to='main.person')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_notifications', to='main.university')),
            ],
            options={
                'verbose_name': 'Групповое оповещение',
                'verbose_name_plural': 'Групповые оповещения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'created_at'], name='main_groupn_group_i_5dd7b1_idx')],
            },
        ),
    ]
