# Generated by Django 5.2.8 on 2025-11-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_applicationrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admissionrequest',
            unique_together={('applicant', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='applicantexam',
            unique_together={('applicant', 'subject', 'exam_type')},
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.applicant'),
        ),
        migrations.AddField(
            model_name='applicantexam',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='main.applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='main.person'),
        ),
        migrations.RemoveField(
            model_name='admissionrequest',
            name='applicant_rating',
        ),
        migrations.RemoveField(
            model_name='applicantexam',
            name='applicant_rating',
        ),
    ]
