# Generated by Django 5.2.8 on 2025-11-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_person_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_login',
        ),
    ]
